### ISSUE TITLE
[Android] The error state is not dismissed when a valid selection is made 

### ISSUE THREAD

**Issue by Romana-Nan** [nventive/UnoApplicationTemplate#106]
## Expected Behavior

The error state should be dismissed when a valid selection is made 

## Actual Behavior

 The error state is not dismissed when a valid selection is made 

![thumbnail_Screenshot_20211112-114935_ApplicationTemplate](https://user-images.githubusercontent.com/73650950/141850939-bbf475a5-56d2-4bd7-ba1a-8189b8edec40.jpg)

## Steps to Reproduce the Problem

1. Launch app
2. On the Welcome page select Create account
3. Tap Create account button
4. An error state is displayed
5. On the last sections (Favorite Donuts) select 3 options
6. Notice the error state is not dismissed  

## Specifications

- Version: https://appcenter.ms/orgs/nventive-framework/apps/Application-Template-Canary-1/distribute/releases/16
- Platform: Android
- Subsystem:

**Comment by carlh98** [comment]
@Romana-Nan I think we can close this issue since the design and data has changed since it was open - And we reopen new bugs in Azure Devops instead, it's going to be clearer this way

**Comment by carlh98** [comment]
Closing because of design changes
