### ISSUE TITLE
[Android] The watermark displayed for Secondary phone number is cut off 

### ISSUE THREAD

**Issue by Romana-Nan** [nventive/UnoApplicationTemplate#108]
## Expected Behavior

The watermark should not be cut 

## Actual Behavior

The watermark displayed for Secondary phone number is cut off 

![thumbnail_Screenshot_20211112-115113_ApplicationTemplate](https://user-images.githubusercontent.com/73650950/141850101-128e3877-8c25-437b-a77b-3f21f7611fd3.jpg)

## Steps to Reproduce the Problem

1. Launch app
2. On the Welcome page select Create account
3.  Scroll down to Secondary phone number
4. Notice the Watermark displayed
5. Enter any value and tap another field 
6. Notice the Watermark displayed 

## Specifications

- Version: https://appcenter.ms/orgs/nventive-framework/apps/Application-Template-Canary-1/distribute/releases/16
- Platform: Android
- Subsystem:

**Comment by simonamisca** [comment]
Closed due to design change
