### ISSUE TITLE
[Android] Returning from one of the Settings options, one of the Settings button has a selected state 

### ISSUE THREAD

**Issue by Romana-Nan** [nventive/UnoApplicationTemplate#109]
## Expected Behavior

An unselected button should not display a selected state 

## Actual Behavior

Returning from one of the Settings options, one of the Settings button has a selected state 

![thumbnail_Screenshot_20211112-121120_ApplicationTemplate](https://user-images.githubusercontent.com/73650950/141849282-bc22fe12-671c-455e-8707-a5bf92908e08.jpg)

**NOTE**

Related issue
https://github.com/nventive/UnoApplicationTemplate/issues/111

## Steps to Reproduce the Problem

1. Launch app
2. From the Welcome page select Continue
3. From the bottom navigation bar select Settings 
4. Tap any option from the setting page (ex. Login)
5. On the Login screen tap Android back button
6. The Settings page should be displayed
7. Notice the options displayed
8. One of the options (Ex. terms and conditions) has s selected state 

## Specifications

- Version: https://appcenter.ms/orgs/nventive-framework/apps/Application-Template-Canary-1/distribute/releases/16
- Platform: Android
- Subsystem:

**Comment by simonamisca** [comment]
Closed due to design change
