### ISSUE TITLE
[ALL] New application template - Splashscreen does not dismiss 

### ISSUE THREAD

**Issue by vincentcastagna** [nventive/UnoApplicationTemplate#18]
## Expected Behavior

- Splashscreen should be dismissed 

## Actual Behavior

- Splashscreen is not dismissed 

## Steps to Reproduce the Problem

1. create a new project with dotnet new nv-mobile -n projectName
2. Build
3. Run on UWP/iOS/Android 
4. Notice the splashscreen is not dismissed but still gives input to underlying elements 
5. Confirmed this bug by removing the splashscreen element from the shell once app booted. 

The issue is caused by the fact we do not have the dismiss in the CoreStartup.cs 

```
#if __MOBILE__ || WINDOWS_UWP
			var dispatcher = services.GetRequiredService<CoreDispatcher>();

			_ = dispatcher.RunAsync(CoreDispatcherPriority.Normal, DismissSplashScreen);

			void DismissSplashScreen() // Runs on UI thread
			{
				Shell.Instance.ExtendedSplashScreen.Dismiss();
			}
#endif
```

## Specifications

VS 2019 
Uno app template latest

**Comment by MatFillion** [comment]
https://github.com/nventive/UnoApplicationTemplate/pull/14/files#r485917577

**Comment by jcantin-nventive** [comment]
Solved with https://github.com/nventive/UnoApplicationTemplate/pull/19
