### ISSUE TITLE
[ios] App freeze when navigating with Uno 3.0+

### ISSUE THREAD

**Issue by carlh98** [nventive/UnoApplicationTemplate#28]
## Expected Behavior
App does not freeze

## Actual Behavior
App freeze when navigating to a page with AppBarButton containing a Path

## Steps to Reproduce the Problem

1. Use branch dev/cama/update
2. Navigate to the settings page
3. Notice that the app becomes unresponsive 

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by jeanplevesque** [comment]
@carlh98 is this still relevant?

**Comment by carlh98** [comment]
@jeanplevesque Will look into this!
