### ISSUE TITLE
dotnet new nvmobile -n Applicita.CapsuleCRMTagManager produces code which does'nt build

### ISSUE THREAD

**Issue by johnkattenhorn** [nventive/UnoApplicationTemplate#325]
## Expected Behavior

dotnet new nvmobile -n Applicita.CapsuleCRMTagManager produces code which should compile without any changes.

## Actual Behavior

dotnet new nvmobile -n Applicita.CapsuleCRMTasgManager produces code which won't compile, some files are missing namespaces; for example `IConfiguration.Extentions.cs`

## Steps to Reproduce the Problem

1. Git Clone the Latest Build from Repo / Main
2. Install using `dotnet new install ./`
3. Check the install was completed using `dotnet new list`
4. `dotnet new nvmobile -n Applicita.CapsuleCRMTagManager` to create new project
5. Open generated solution in Visual Studio 2022
6. Build All 

## Specifications

- Version: Visual Studio 17.6.2
- Platform: Windows 11
- Subsystem:

PS. Not sure how to check for Uno version - uno-check is up to date and I ran this

**Comment by Soap-141** [comment]
@johnkattenhorn Can you show us a screenshot of the file with missing namespace? Does the cloned repository build?

**Comment by johnkattenhorn** [comment]
OK, so I tried to build the clone repository, and that's failing on one project (there are quite a few warnings too); see below:

<img width="1302" alt="image" src="https://github.com/nventive/UnoApplicationTemplate/assets/616249/847502ae-1ff7-4dfa-85cc-885a6ff4361a">

<img width="1324" alt="image" src="https://github.com/nventive/UnoApplicationTemplate/assets/616249/45257802-fb7b-413e-930a-9e4ae35d1058">

I think I might have found the potential issue, though, if you remove the period `(.)` between Applicita and CapsuleCRM then then `public static class Applicita.CapsuleCRMTagManagerConfigurationExtensions` becomes `public static class ApplicitaCapsuleCRMTagManagerConfigurationExtensions`, which now builds as the `Applicita.` is not being interpreted as a namespace.

FYI - It's our conventions to use `[CompanyName].[ProductName].[ProjectName]`

**Comment by Soap-141** [comment]
@jeanplevesque @carlh98

**Comment by jeanplevesque** [comment]
@johnkattenhorn @Soap-141 
Right, that's a known issue.
We should update the documentation to specify avoiding the usage of periods (`.`) in the name parameter, at least until we fix this.

**Comment by johnkattenhorn** [comment]
OK, I've seen this before with other templates, we can work around it. Let's close this.
