### ISSUE TITLE
Access tokens may be refreshed concurrently

### ISSUE THREAD

**Issue by fperreaultnv** [nventive/UnoApplicationTemplate#86]
## Expected Behavior
If an access token is expired, the auth system of the app template should block all the api calls until the access token is properly refreshed, and then proceed with unblocking the calls.

## Actual Behavior
If an access token is expired, the auth system of the app template tries to refresh the accesstoken concurrently.

## Steps to Reproduce the Problem

1. Have an app for which the home page will fetch data from many endpoints/make multiple concurrent api calls, and be authenticated on this app.
2. Close the app and wait for your access token to be expired
3. Launch the app and notice all the api calls are trying to refresh the access token at the same time

## Specifications

- Version: a1508613
- Platform: *
- Subsystem:

**Comment by carlh98** [comment]
@fperreaultnv this issue can be closed?

**Comment by Soap-141** [comment]
> @fperreaultnv this issue can be closed?

@carlh98 @jeanplevesque @MatFillion

**Comment by jeanplevesque** [comment]
Resolved by #88
